MpwToolLibs68k = ¶
					"{Libraries}Stubs.o"				¶
					"{CLibraries}StdCLib.o"				¶
					"{Libraries}MacRuntime.o"			¶
					"{Libraries}IntEnv.o"				¶
					"{Libraries}Interface.o"			¶

SiowLibsPPC = ¶
					"{PPCLibraries}PPCSIOW.o"			¶
					"{PPCLibraries}MrCPlusLib.o"		¶
					"{SharedLibraries}InterfaceLib"		¶
					"{SharedLibraries}StdCLib"			¶
					"{SharedLibraries}MathLib"			¶
					"{PPCLibraries}PPCCRuntime.o"		¶

PPCCOptions = -w 2

IM = :Intermediates:
Apps = :Apps:

{IM}								Ä	:

{IM}RomWedge.x						Ä	{IM}WedgeStub.s.x {IM}printf.c.x {IM}Wedge.c.x
	PPCLink -outputformat xcoff -codeorder source -roistext on -o {Targ} {Deps}

{IM}Linker							Ä	{IM}Linker.c.o
	ILink -d -t 'MPST' -c 'MPS ' -o {Targ} {MpwToolLibs68k} {Deps}

{Apps}TestWedge						Ä	{IM}Wedge.c.x {IM}NKShim.s.x
	PPCLink -d -t 'APPL' -c 'siow' -o {Targ} {Deps} {SiowLibsPPC}
	Rez -a "{RIncludes}SIOW.r" -d DEFAULT_SAVE_PREF=1 -o {Targ}

{Apps}WedgeLogReader				Ä	{IM}WedgeLogReader.c.x
	PPCLink -d -t 'APPL' -c 'siow' -o {Targ} {Deps} {SiowLibsPPC}
	Rez -a "{RIncludes}SIOW.r" -d DEFAULT_SAVE_PREF=1 -o {Targ}
